#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#

"""
Plays a generated scenario in a real Talk call and records it.

Each participant is a Talkbuchet virtual participant running in its own browser
and publishing the audio generated by generate_audio.py. The audio of all the
participants is scheduled to start at the same wall clock time, so the call
reproduces the scripted timing exactly.

The recording is started and stopped through the Talk API by a moderator of the
conversation, who will be the owner of the recording and of its transcript. If
--wait-transcript is given the new transcript (and summary) drafts are
downloaded once available.

A High Performance Backend and a recording server must be configured.

Usage:
    ./run_call.py AUDIO_DIRECTORY --url https://cloud.example.com --token TOKEN \\
        --moderator admin [--moderator-password APP_PASSWORD, or $TALK_APP_PASSWORD] \\
        [--credentials credentials.json] [--browser chrome|firefox] [--headless] \\
        [--wait-transcript 30]

The credentials file maps participant ids to {"user", "appToken"}; participants
without credentials join as guests.
"""

import argparse
import base64
import calendar
import json
import os
import re
import time
from pathlib import Path

import requests
from selenium import webdriver

TALKBUCHET = Path(__file__).resolve().parents[2] / 'docs' / 'Talkbuchet.js'

TALKBUCHET_EXPORTS = '''
window.setCredentials = setCredentials
window.setToken = setToken
window.startMedia = startMedia
window.startVirtualParticipant = startVirtualParticipant
window.stopVirtualParticipant = stopVirtualParticipant
window.sendNickThroughDataChannel = sendNickThroughDataChannel
window.sendSpeakingStateThroughDataChannel = sendSpeakingStateThroughDataChannel
'''

SCHEDULE_SPEAKING = '''
for (const [time, speaking] of arguments[1]) {
    setTimeout(() => sendSpeakingStateThroughDataChannel(speaking), arguments[0] + time * 1000 - Date.now())
}
'''

FAKE_MEDIA = '''
const data = Uint8Array.from(atob(arguments[0]), (character) => character.charCodeAt(0)).buffer
const audioContext = new AudioContext()
await audioContext.resume()
const buffer = await audioContext.decodeAudioData(data)
const destination = audioContext.createMediaStreamDestination()
navigator.mediaDevices.getUserMedia = async () => destination.stream
window.scheduleFakeAudio = (startEpochMs) => {
    const source = audioContext.createBufferSource()
    source.buffer = buffer
    source.connect(destination)
    const delay = Math.max(0, (startEpochMs - Date.now()) / 1000)
    source.start(audioContext.currentTime + delay)
    return delay
}
'''

RECORDING_NONE = 0
RECORDING_ACTIVE = (1, 2)
RECORDING_FAILED = 5


def executeAsync(driver, script, *arguments):
    wrapped = 'const done = arguments[arguments.length - 1]; (async () => { ' + script + ' })().then(done, (error) => done({error: String(error)}))'
    result = driver.execute_async_script(wrapped, *arguments)
    if isinstance(result, dict) and 'error' in result:
        raise RuntimeError(result['error'])
    return result


class TalkApi:

    def __init__(self, url, token, user, password):
        self._base = url.rstrip('/') + '/ocs/v2.php/apps/spreed/api'
        self._token = token
        self._session = requests.Session()
        self._session.auth = (user, password)
        self._session.headers.update({'OCS-APIRequest': 'true', 'Accept': 'application/json'})

    def _request(self, method, path, **kwargs):
        response = self._session.request(method, self._base + path, timeout=30, **kwargs)
        if response.status_code >= 400:
            raise RuntimeError(f'{method} {path} failed with {response.status_code}: {response.text[:500]}')
        return response.json()['ocs']['data']

    def callRecording(self):
        return self._request('GET', f'/v4/room/{self._token}')['callRecording']

    def startRecording(self):
        self._request('POST', f'/v1/recording/{self._token}', data={'status': 2})

    def stopRecording(self):
        self._request('DELETE', f'/v1/recording/{self._token}')

    def listArtifacts(self):
        return self._request('GET', f'/v1/recording/{self._token}/artifacts')

    def getArtifact(self, artifactId):
        return self._request('GET', f'/v1/recording/{self._token}/artifact/{artifactId}')

    def waitForRecording(self, accepted, timeout):
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            status = self.callRecording()
            if status in accepted:
                return status
            if status == RECORDING_FAILED:
                raise RuntimeError('The recording failed')
            time.sleep(1)
        raise RuntimeError(f'Timeout waiting for recording status {accepted}')


def newDriver(browser, headless):
    if browser == 'firefox':
        options = webdriver.FirefoxOptions()
        options.set_preference('media.navigator.permission.disabled', True)
        options.set_preference('media.autoplay.default', 0)
        if headless:
            options.add_argument('-headless')
        return webdriver.Firefox(options=options)

    options = webdriver.ChromeOptions()
    options.add_argument('--use-fake-ui-for-media-stream')
    options.add_argument('--autoplay-policy=no-user-gesture-required')
    if headless:
        options.add_argument('--headless=new')
    return webdriver.Chrome(options=options)


def startParticipant(driver, args, participant, credentials, audioFileName):
    driver.set_script_timeout(120)
    driver.get(args.url.rstrip('/') + '/status.php')

    with open(audioFileName, 'rb') as audioFile:
        executeAsync(driver, FAKE_MEDIA, base64.b64encode(audioFile.read()).decode('ascii'))

    executeAsync(driver, TALKBUCHET.read_text(encoding='utf-8') + TALKBUCHET_EXPORTS)

    user = credentials.get(participant['id'], {})
    executeAsync(driver, '''
        await startMedia(true, false)
        setToken(arguments[0])
        if (arguments[1]) {
            setCredentials(arguments[1], arguments[2])
        }
        await startVirtualParticipant()
    ''', args.token, user.get('user'), user.get('appToken'))

    if not user:
        # Guests have no display name otherwise, so the transcript could not
        # show their names.
        executeAsync(driver, '''
            const response = await fetch(arguments[0], {
                method: 'POST',
                headers: {'OCS-APIRequest': 'true', 'Content-Type': 'application/json'},
                body: JSON.stringify({displayName: arguments[1]}),
            })
            if (!response.ok) {
                throw new Error('Setting the guest name failed with ' + response.status)
            }
        ''', args.url.rstrip('/') + f'/ocs/v2.php/apps/spreed/api/v1/guest/{args.token}/name', participant['name'])

    # The actor id identifies the participant in the transcript if its name
    # is not known there.
    return executeAsync(driver, '''
        const response = await fetch(arguments[0], {headers: {'OCS-APIRequest': 'true', 'Accept': 'application/json'}})
        return (await response.json()).ocs.data.actorId
    ''', args.url.rstrip('/') + f'/ocs/v2.php/apps/spreed/api/v4/room/{args.token}')


def sendNick(driver, name):
    try:
        driver.execute_script('sendNickThroughDataChannel(arguments[0])', name)
    except Exception as exception:
        print(f'Could not send nick {name}: {exception}')


def speakingEvents(turns, startLatency, stopLatency):
    """
    Returns the [time, speaking] events a real client would send for the turns.

    Real clients detect speaking from the audio level (hark), so the events
    arrive a bit after the speech starts, and "stoppedSpeaking" is only sent
    after a period of silence; a new turn of the same speaker before that just
    continues the previous one.
    """
    intervals = []
    for turn in sorted(turns, key=lambda turn: turn['start']):
        start = turn['start'] + startLatency
        end = turn['end'] + stopLatency
        if intervals and start <= intervals[-1][1]:
            intervals[-1][1] = max(intervals[-1][1], end)
        else:
            intervals.append([start, end])

    events = []
    for start, end in intervals:
        events += [[round(start, 3), True], [round(end, 3), False]]
    return events


def recordingEpoch(fileName):
    """Start of the recording, from its file name (named in UTC by the recording server)."""
    match = re.search(r'(\d{4}-\d{2}-\d{2} \d{2}-\d{2}-\d{2})', fileName)
    return calendar.timegm(time.strptime(match.group(1), '%Y-%m-%d %H-%M-%S')) if match else None


def waitForTranscript(api, knownIds, timeout, output, recordingStartedEpoch):
    deadline = time.monotonic() + timeout
    found = {}
    while time.monotonic() < deadline and 'transcript' not in found:
        for item in api.listArtifacts():
            if item['id'] in knownIds or item['type'] in found:
                continue
            artifact = api.getArtifact(item['id'])
            # Drafts of earlier recordings may be finished during this run.
            epoch = recordingEpoch(artifact['fileName'])
            if epoch is not None and epoch < recordingStartedEpoch - 60:
                knownIds.add(item['id'])
                continue
            found[item['type']] = artifact
        if 'transcript' not in found:
            time.sleep(15)

    for artifactType, artifact in found.items():
        with open(os.path.join(output, artifactType + '.md'), 'w', encoding='utf-8') as artifactFile:
            artifactFile.write(artifact['content'])
        print(f'Saved {artifactType} draft {artifact["id"]} ({artifact["fileName"]})')

    if 'transcript' not in found:
        print('Timeout waiting for the transcript draft')


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('audio', help='Directory created by generate_audio.py')
    parser.add_argument('--url', required=True)
    parser.add_argument('--token', required=True)
    parser.add_argument('--moderator', required=True)
    parser.add_argument('--moderator-password', default=os.environ.get('TALK_APP_PASSWORD'),
                        help='App password of the moderator (defaults to $TALK_APP_PASSWORD)')
    parser.add_argument('--credentials')
    parser.add_argument('--browser', choices=['chrome', 'firefox'], default='chrome')
    parser.add_argument('--headless', action='store_true')
    parser.add_argument('--settle', type=float, default=10, help='Seconds to wait after the participants joined')
    parser.add_argument('--lead', type=float, default=8, help='Seconds between the recording start and the audio start')
    parser.add_argument('--no-speaking-events', action='store_true',
                        help='Do not send the "speaking" data channel messages that real clients send')
    parser.add_argument('--speaking-start-latency', type=float, default=0.15,
                        help='Seconds between the start of a turn and its "speaking" message')
    parser.add_argument('--speaking-stop-latency', type=float, default=1.5,
                        help='Seconds between the end of a turn and its "stoppedSpeaking" message')
    parser.add_argument('--linger', type=float, default=20,
                        help='Seconds the participants stay in the call after the recording stopped')
    parser.add_argument('--wait-transcript', type=float, default=0, help='Minutes to wait for the transcript draft')
    args = parser.parse_args()

    if not args.moderator_password:
        parser.error('--moderator-password or $TALK_APP_PASSWORD is required')

    with open(os.path.join(args.audio, 'expected.json'), encoding='utf-8') as expectedFile:
        expected = json.load(expectedFile)
    credentials = {}
    if args.credentials:
        with open(args.credentials, encoding='utf-8') as credentialsFile:
            credentials = json.load(credentialsFile)

    api = TalkApi(args.url, args.token, args.moderator, args.moderator_password)
    knownArtifactIds = {item['id'] for item in api.listArtifacts()}

    drivers = {}
    actorIds = {}
    try:
        for participant in expected['participants']:
            print(f'Joining {participant["name"]}')
            driver = newDriver(args.browser, args.headless)
            drivers[participant['id']] = driver
            actorIds[participant['id']] = startParticipant(driver, args, participant, credentials,
                                                           os.path.join(args.audio, participant['id'] + '.wav'))

        time.sleep(args.settle)
        for participant in expected['participants']:
            sendNick(drivers[participant['id']], participant['name'])

        print('Starting recording')
        api.startRecording()
        api.waitForRecording(RECORDING_ACTIVE, 120)
        recordingStartedEpoch = time.time()

        startEpochMs = int((time.time() + args.lead) * 1000)
        for participant in expected['participants']:
            sendNick(drivers[participant['id']], participant['name'])
            drivers[participant['id']].execute_script('return scheduleFakeAudio(arguments[0])', startEpochMs)
            if not args.no_speaking_events:
                ownTurns = [turn for turn in expected['turns'] if turn['speaker'] == participant['id']]
                events = speakingEvents(ownTurns, args.speaking_start_latency, args.speaking_stop_latency)
                drivers[participant['id']].execute_script(SCHEDULE_SPEAKING, startEpochMs, events)

        print(f'Playing the scenario ({expected["duration"]:.0f} s)')
        time.sleep(max(0, startEpochMs / 1000 - time.time()) + expected['duration'] + 3)

        print('Stopping recording')
        api.stopRecording()
        api.waitForRecording((RECORDING_NONE,), 300)
        # Like in a real meeting the participants do not leave right after the
        # recording stopped, while the recording is uploaded.
        time.sleep(args.linger)

        with open(os.path.join(args.audio, 'run.json'), 'w', encoding='utf-8') as runFile:
            json.dump({
                'token': args.token,
                'recordingStartedEpoch': recordingStartedEpoch,
                'audioStartEpoch': startEpochMs / 1000,
                'expectedOffset': round(startEpochMs / 1000 - recordingStartedEpoch, 3),
                'speakingEvents': not args.no_speaking_events,
                'participants': [{**participant, 'actorId': actorIds.get(participant['id'])} for participant in expected['participants']],
            }, runFile, indent=2)
    finally:
        for driver in drivers.values():
            try:
                driver.execute_script('stopVirtualParticipant()')
            except Exception:
                pass
            driver.quit()

    if args.wait_transcript > 0:
        print('Waiting for the transcript')
        waitForTranscript(api, knownArtifactIds, args.wait_transcript * 60, args.audio, recordingStartedEpoch)


if __name__ == '__main__':
    main()
